name: amuga
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.12.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  font_awesome_flutter: ^9.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  http: ^0.13.3
  intl: ^0.17.0
  autocomplete_textfield: ^1.7.3
  geolocator: ^7.0.3
  flutter_spinkit: ^4.1.2
  provider: ^5.0.0
  sembast: ^3.0.2
  device_info: ^2.0.0
  timelines: ^0.1.0
  path_provider: ^2.0.1
  polyline: ^1.0.2
  webview_flutter: ^2.0.9
  package_info: ^2.0.2
  vibration: ^1.7.3
  vibration_web: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gtfs.sqlite
    - assets/CGU.html
    - assets/apropos.html
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: SpaceAge
      fonts:
        - asset: fonts/space-age.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
